# Site settings
title: Wanglinzhizhi 
email: wanglinzhizhi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  游走在上下文无关文法间
baseurl: "" # the subpath of your site, e.g. /blog/ 
github_username:  wagnlinzh


# Build settings
markdown: kramdown
# markdown: redcarpet
# highlighter: pygments
highlighter: rouge
# permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
